
function PrecacheResourceModel ( context )

	--hero
	local heroList = LoadKeyValues("scripts/npc/herolist.txt")
    for k,v in pairs (heroList) do        
        PrecacheResource('model', GetUnitKV(heroList[k], "Model"), context)
    end

    local heroTest = LoadKeyValues("scripts/npc/herotest.txt")
    for k,v in pairs (heroTest) do        
        PrecacheResource('model', GetUnitKV(heroTest[k], "Model"), context)
    end

    --master 
    PrecacheResource("model", "models/rin/rin.vmdl", context)
    PrecacheResource("model", "models/shirou/shirou.vmdl", context)
    --PrecacheResource("model", "models/altera/altera.vmdl", context)

    --Prop 
    --PrecacheResource("model", "models/archer/kanshou.vmdl", context)
    --PrecacheResource("model", "models/archer/byakuya.vmdl", context)
    --PrecacheResource("model", "models/astolfo/astolfo_sword.vmdl", context)  
    --PrecacheResource("model", "models/astolfo/astolfo_new_horn.vmdl", context)  
    --PrecacheResource("model", "models/astolfo/astolfo_scabbard.vmdl", context)  
    --PrecacheResource("model", "models/astolfo/astolfo_lance.vmdl", context)  
    --PrecacheResource("model", "models/kuro/kuro_bow.vmdl", context)  
    --PrecacheResource("model", "models/lubu/lubu_bow.vmdl", context)  
    --PrecacheResource("model", "models/lubu/lubu_lance2.vmdl", context)  
    --PrecacheResource("model", "models/lubu/lubu_arrow2.vmdl", context)  
    --PrecacheResource("model", "models/lancelot/lancelot_rod.vmdl", context)  
    --PrecacheResource("model", "models/lancelot/lancelot_arondite.vmdl", context)  
    --PrecacheResource("model", "models/lancelot/lancelot_gun_by_zefiroft.vmdl", context)  
    --PrecacheResource("model", "models/bathory/bathory_weapon.vmdl", context)  
    --PrecacheResource("model", "models/okita/okita_scabbard.vmdl", context)
    --PrecacheResource("model", "models/okita/okita_sword.vmdl", context)
    --PrecacheResource("model", "models/scathach/scat_gae.vmdl", context)
    --PrecacheResource("model", "models/drake/drake_sword.vmdl", context)
    --PrecacheResource("model", "models/drake/drake_gun1.vmdl", context)
    --PrecacheResource("model", "models/drake/drake_gun2.vmdl", context)
    --PrecacheResource("model", "models/drake/drake_boat.vmdl", context)

    --event 
    PrecacheResource('model', "models/padoru/padoru_alter.vmdl", context)

    --skill 
    --PrecacheResource("model", "models/iskandar/default/iskandar_gordius.vmdl", context)  
    --PrecacheResource("model", "models/iskandar/salary/iskandar_salary_gordius.vmdl", context)  
    --PrecacheResource("model", "models/bathory/default/bathory_wing_by_zefiroft.vmdl", context)  
    --PrecacheResource("model", "models/bathory/school/bathory_schoolgirl_wing_by_zefiroft.vmdl", context)  
    --PrecacheResource("model", "models/bathory/hunter/bathory_hunter_wing_by_zefiroft.vmdl", context) 
    PrecacheResource("model", "models/angra_mainyu/avenger_morph_by_zefiroft.vmdl", context)  
    PrecacheResource("model", "models/karna/default/karna_armorless_by_zefiroft.vmdl", context)  
    PrecacheResource("model", "models/updated_by_seva_and_hudozhestvenniy_film_spizdili/mordred/mordred_unanim_face.vmdl", context)  
    PrecacheResource("model", "models/updated_by_seva_and_hudozhestvenniy_film_spizdili/gilgamesh/gilgameshcausalunanimea.vmdl", context)  
    PrecacheResource("model", "models/mordred/summer/summer_mordred_surf_by_zefiroft.vmdl", context)  
    --PrecacheResource("model", "models/konomama_hassan/konomama_hassan.vmdl", context)
    --PrecacheResource("model", "models/femalehassan/femalehassan.vmdl", context)

    --skin
    --[[PrecacheResource('model', "models/updated_by_seva_and_hudozhestvenniy_film_spizdili/gilgamesh/gilgameshcasualunanim.vmdl", context)
    PrecacheResource('model', "models/artoria/casual_saber/casual_saber_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/artoria_alter/saber_alter_casual/artoria_alter_casual_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/mordred/casual/casual_mordred_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/archer/emiya_black/emiya_black_zefiroft.vmdl", context)
    PrecacheResource('model', "models/medusa/medusa_lily_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/vlad/apo/vlad_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/medea/medea_uncape/medea_uncape_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/okita/okita_pink/okita_pink_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/cu_chulainn/cu_extra_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/nero/nero_emperor/nero_emberor_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/atalanta/atalanta_alter/atalanta_alter_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/tamamo/casual/tamamo_casual_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/jeanne/white/white_jeanne_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/lishuwen/gang/lishuwen_gangster_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/astolfo/school/astolfo_school_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/gilles/abyss/gilles_abyss_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/iskandar/salary/iskandar_salary_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/hassan/100face/hassan_100_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/bathory/school/bathory_schoolgirl_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/angra_mainyu/shirou/angra_emiya_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/lancelot/suit/lancelot_suit_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/gawain/samurai/gawain_samurai_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/karna/bartender/karna_bartender_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/nursery_rhyme/alice/nr_alice_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/artoria/crown_saber_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/medea/medea_lily/medea_lily_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/artoria_alter/saber_alter_unarm_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/mordred/mordred_unarmor/mordred_unarmor_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/nero/nero_dress/nero_dress_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/jeanne/santa/jeanna_lily_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/lishuwen/coat/lushuwen_boss_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/astolfo/casual/astolfo_pink_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/gilles/pope/gilles_pope_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/gawain/summer/gawain_summer_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/karna/god/karna_god_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/arthur/arthur_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/scathach/secretary/scat_secretary_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/scathach/gypse/scat_gypsee_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/artoria/suit_saber/artoria_suit_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/nero/nero_king/nero_king_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/lubu/general/lubu_flying_general.vmdl", context)
    PrecacheResource('model', "models/lubu/mecha/mecha_lubu_zefiroft.vmdl", context)
    PrecacheResource('model', "models/drake/captain/drake_captain_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/drake/pirate/drake_pirate_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/drake/cowgirl/drake_cowgirl_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/drake/summer/drake_summer_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/amakusa/samurai/amakusa_rebel_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/artoria/dress_saber/artoria_dress_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/artoria/saber_lily/artoria_lily_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/scathach/summer/scat_summer_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/archer/emiya_shirou/emiya_shirou_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/bathory/hunter/bathory_hunter_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/lancelot/armor/lancelot_curse_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/archer/emiya_cyber/emiya_cyber_by_zefiroft.vmdl", context)
    PrecacheResource('model', "models/kuro/illya_archer/illya_archer_by_zefiroft.vmdl", context)    
    PrecacheResource('model', "models/medusa/illya_rider/illya_rider_by_zefiroft.vmdl", context)  
    PrecacheResource('model', "models/hassan/female_hassan/female_hassan_by_zefiroft.vmdl", context)     
    PrecacheResource('model', "models/cu_chulainn/illya_lancer/illya_lancer_by_zefiroft.vmdl", context)  
    PrecacheResource('model', "models/nero/racing_nero/racing_nero_by_zefiroft.vmdl", context)  
    PrecacheResource('model', "models/tamamo/wedding/wedding_tamamo_by_zefiroft.vmdl", context)   
    PrecacheResource('model', "models/hassan/illya_assassin/illya_assassin_by_zefiroft.vmdl", context)  
    PrecacheResource('model', "models/okita/okita_alter/okita_alter_by_zefiroft.vmdl", context) 
    PrecacheResource('model', "models/archer/emiya_hero/emiya_hero_by_zefiroft.vmdl", context) 
    PrecacheResource('model', "models/archer/muramasa/muramasa_by_zefiroft.vmdl", context) ]]
    
    --unit 
    PrecacheResource("model_folder", "models/heroes/chen", context)
    PrecacheResource("model_folder", "models/heroes/dragon_knight", context)
    --PrecacheResource("model_folder", "models/heroes/chaos_knight", context)
    --PrecacheResource("model_folder", "models/heroes/silencer", context)
    PrecacheResource("model_folder", "models/heroes/windrunner", context)
    --PrecacheResource("model_folder", "models/heroes/juggernaut", context)
    --PrecacheResource('model', "models/items/chaos_knight/blade_of_entropy/blade_of_entropy.vmdl", context)
    --PrecacheResource('model', "models/items/chaos_knight/chaos_legion_helm/chaos_legion_helm.vmdl", context)
    --PrecacheResource('model', "models/items/chaos_knight/rising_chaos_steed/rising_chaos_steed.vmdl", context)
    PrecacheResource('model', "models/items/windrunner/sparrowhawk_hood2/sparrowhawk_hood2.vmdl", context)
    --PrecacheResource('model', "models/items/silencer/whispertribunal__weapon/whispertribunal__weapon.vmdl", context)
    --PrecacheResource('model', "models/items/silencer/whispertribunal_arms/whispertribunal_arms.vmdl", context)
    --PrecacheResource('model', "models/items/silencer/whispertribunal_belt/whispertribunal_belt.vmdl", context)
   -- PrecacheResource('model', "models/items/silencer/whispertribunal_head/whispertribunal_head.vmdl", context)
    --PrecacheResource('model', "models/items/silencer/whispertribunal_shield/whispertribunal_shield.vmdl", context)
    --PrecacheResource('model', "models/items/silencer/whispertribunal_shoulder/whispertribunal_shoulder.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/bladesrunner_arms/bladesrunner_arms.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/bladesrunner_back/bladesrunner_back.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/bladesrunner_head/bladesrunner_head.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/bladesrunner_legs/bladesrunner_legs.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/bladesrunner_weapon/bladesrunner_weapon.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/sinister_shadow_arms/sinister_shadow_arms.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/sinister_shadow_back/sinister_shadow_back.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/sinister_shadow_head/sinister_shadow_head.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/sinister_shadow_legs/sinister_shadow_legs.vmdl", context)
    --PrecacheResource('model', "models/items/juggernaut/sinister_shadow_weapon/sinister_shadow_weapon.vmdl", context)
    PrecacheResource("model", "models/avenger/trueform/trueform.vmdl", context)  
    PrecacheResource("model", "models/musashi/niou_by_zefiroft.vmdl", context) 
    --PrecacheResource("model", "models/bathory/bathory_iron_maiden.vmdl", context)  
    --PrecacheResource("model", "models/drake/drake_golden_hind.vmdl", context)  
    --PrecacheResource("model", "models/drake/drake_boat.vmdl", context)  
    --PrecacheResource("model", "models/drake/drake_wild_hunt.vmdl", context)
    --PrecacheResource("model", "models/drake/drake_cannon.vmdl", context)    
    PrecacheResource("model", "models/items/courier/echo_wisp/echo_wisp_flying.vmdl", context) 
    PrecacheResource("model", "models/zc/tidehuntertentacle_reference.vmdl", context) 
    PrecacheResource("model", "models/zc/tentacleking.vmdl", context) 
    --PrecacheResource("model", "models/okita/okita_flag.vmdl", context) 
    --PrecacheResource("model", "models/scathach/scathach_gate_of_sky.vmdl", context) 
    PrecacheResource("model", "models/iskander/waver.vmdl", context) 
    --[[PrecacheUnitByNameSync("okita_shinsengumi", context)
    PrecacheUnitByNameSync("okita_hijikata", context)
    PrecacheUnitByNameSync("okita_flag", context)
    PrecacheUnitByNameSync("gille_oceanic_demon", context)
    PrecacheUnitByNameSync("gilles_cthulhu_tentacle", context)
    PrecacheUnitByNameSync("gille_tentacle_of_destruction", context)
    PrecacheUnitByNameSync("iskandar_infantry", context)
    PrecacheUnitByNameSync("iskandar_archer", context)
    PrecacheUnitByNameSync("iskandar_eumenes", context)
    PrecacheUnitByNameSync("iskandar_cavalry", context)
    PrecacheUnitByNameSync("iskandar_hephaestion", context)
    PrecacheUnitByNameSync("iskandar_mage", context)
    PrecacheUnitByNameSync("iskandar_waver", context)
    PrecacheUnitByNameSync("sight_dummy_unit", context)
    PrecacheUnitByNameSync("dummy_unit", context)]]
    
    print('precache model done')
end

function PrecacheResourceParticle ( context )

    -- General 
    PrecacheResource( "particle", "particles/custom/system/damage_popup.vpcf", context)
    PrecacheResource( "particle", "particles/custom/system/damage_popup_magical.vpcf", context)
    PrecacheResource( "particle", "particles/custom/system/damage_popup_physical.vpcf", context)
    PrecacheResource( "particle", "particles/custom/system/damage_popup_pure.vpcf", context)
    PrecacheResource( "particle", "particles/custom/system/gold_popup.vpcf", context)
    PrecacheResource( "particle", "particles/units/heroes/hero_silencer/silencer_global_silence_sparks.vpcf", context)
    PrecacheResource( "particle", 'particles/units/heroes/hero_chaos_knight/chaos_knight_weapon_blur.vpcf', context)
    PrecacheResource("particle", "particles/econ/items/sven/sven_ti7_sword/sven_ti7_sword_spell_great_cleave_gods_strength.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/juggernaut/jugg_ti8_sword/juggernaut_ti8_sword_attack_a.vpcf", context)
    PrecacheResource("particle", "particles/econ/items/juggernaut/jugg_ti8_sword/juggernaut_ti8_sword_attack_b.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_juggernaut/jugg_attack_blur.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_life_stealer/life_stealer_open_wounds.vpcf", context)
    
    
    -- screen 
    PrecacheResource("particle", "particles/custom/screen_red_splash.vpcf", context)

    -- Mordred 
    PrecacheResource("particle", "particles/custom/mordred/gods_resolution/gods_resolution_active_circle.vpcf", context)
    PrecacheResource("particle", "particles/custom/mordred/purge_the_unjust/ruler_purge_the_unjust_a.vpcf", context)
    PrecacheResource("particle", "particles/custom/mordred/zuus_lightning_bolt.vpcf", context)
    PrecacheResource("particle", "particles/mordred/mordred_clarent_beam.vpcf", context)
    PrecacheResource("particle", "particles/mordred/mordred_clarent_beam_pepeg.vpcf", context)
    PrecacheResource("particle", "particles/custom/caster/caster_argos_durability.vpcf", context)
    PrecacheResource("particle", "particles/custom/mordred/zuus_arc_lightning.vpcf", context)
    PrecacheResource("particle", "particles/custom/mordred/zuus_static_field.vpcf", context)
    PrecacheResource("particle", "particles/custom/mordred/max_excalibur/shockwave.vpcf", context)
    PrecacheResource("particle", "particles/custom/mordred/max_excalibur/charge.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_techies/techies_blast_off.vpcf", context)
    PrecacheResource("particle", "particles/custom/tamamo/gust_heaven_arc_lightning.vpcf", context)
    PrecacheResource("particle", "particles/custom/tamamo/gust_heaven_static.vpcf", context)
    PrecacheResource("particle", "particles/custom/tamamo/frigid_heaven.vpcf", context)
    PrecacheResource("particle", "particles/ui_mouseactions/custom_range_finder_cone.vpcf", context)
    PrecacheResource("particle", "particles/units/heroes/hero_abaddon/abaddon_death_coil_explosion.vpcf", context) 

    --PrecacheResource("particle_folder", "particles/custom/tamamo", context)
    --PrecacheResource("particle_folder", "particles/custom/vlad", context)
    --PrecacheResource("particle_folder", "particles/custom/bathory", context)
    --PrecacheResource("particle_folder", "particles/custom/fran", context)
    --PrecacheResource("particle_folder", "particles/custom/gilles", context)
    --PrecacheResource("particle_folder", "particles/custom/drake", context)
end