"DOTAHeroes"
{
	//=======================================
	//	White Saber(Extra) - Gawain
	//=======================================
	"npc_dota_hero_gawain"
	{
		"override_hero"					"npc_dota_hero_omniknight"
		"DisableWearables" 				"1"
		"Model"							"models/gawain/gawain.vmdl"
		//"Model"						"models/development/invisiblebox.vmdl"
		"ModelScale"					"1.20"
		//"HeroID"						"127"
		"DrawParticlesWhileHidden" 		"1"

		"AbilityLayout"					"6"
		"Ability1"						"gawain_blade_of_the_devoted"
		"Ability2"						"gawain_light_of_galatine"
		"Ability3"						"gawain_sun_of_galatine"
		"Ability4"						"fate_empty1"		
		"Ability5"						"fate_empty8"
		"Ability6"						"gawain_excalibur_galatine"
		"Ability7"						"gawain_numeral_saint"
		"Ability8"						"gawain_blessing_of_fairy"
		"Ability9"						"gawain_excalibur_galatine_detonate"
		"Ability10"						"gawain_blade_of_the_devoted_light"
		"Ability11"						"gawain_excalibur_galatine_light"
		"Ability12"						"gawain_combo_excalibur_galatine"
		"Ability13"						"presence_detection_passive"
		"Ability14"						"attribute_bonus_custom"

		"Combo"							"gawain_combo_excalibur_galatine"
		"AttributeNumber"				"5"
		"Attribute1"					"gawain_attribute_blessing_of_fairy"
		"Attribute2"					"gawain_attribute_nightless_charisma"
		"Attribute3"					"gawain_attribute_numeral_saint"
		"Attribute4"					"gawain_attribute_belt"
		"Attribute5"					"gawain_attribute_kots"
		"ManaCost"						"10"

		"StatusHealth"					"1400"
		"StatusHealthRegen"				"6.0"
		"StatusMana"					"1000"
		"StatusManaRegen"				"5.0"
		
		"ArmorPhysical"					"7"
		"MagicalResistance"				"15"
		
		"AttackCapabilities"			"DOTA_UNIT_CAP_MELEE_ATTACK"
		"AttackRange"					"150"
		"AttackDamageMin"				"47"
		"AttackDamageMax"				"57"
		"AttackRate"					"0.9"
		
		"AttributePrimary"				"DOTA_ATTRIBUTE_STRENGTH"
		"AttributeBaseStrength"			"0"
		"AttributeStrengthGain"			"2.4"
		"AttributeBaseAgility"			"0"
		"AttributeAgilityGain"			"1.4"
		"AttributeBaseIntelligence"		"0"
		"AttributeIntelligenceGain"		"1.2"
		
		"MovementSpeed"					"330"
		"MovementTurnRate"				"0.8"

		"VisionDaytimeRange"			"950"
		"VisionNighttimeRange"			"950"
	}
}