"DOTAAbilities"
{
	//=======================================
	// Berserker - Roar
	//=======================================
	"atalanta_roar"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_roar"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_roar"

		"AbilityCastRange"				"600 650 700 750 800"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"100"

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_FLOAT"
				"duration"				"2 2.5 3 3.5 4"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"ms_slow"				"20 25 30 35 40"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"distance"				"600 650 700 750 800"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"width"					"200"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"base_stacks"			"1 2 3 4 5"
			}
			"06"
			{
				"var_type"				"FIELD_INTEGER"
				"base_damage"			"100 175 250 325 400"
			}
			"07"
			{
				"var_type"				"FIELD_INTEGER"
				"echo_damage"			"100"
			}
			"08"
			{
				"var_type"				"FIELD_INTEGER"
				"as_slow"				"50 70 90 110 130"
			}
			"09"
			{
				"var_type"				"FIELD_INTEGER"
				"cast_range"			"450"
			}
			"10"
			{
				"var_type"				"FIELD_FLOAT"
				"duration_locked"			"1 1.25 1.5 1.75 2"
			}
		}
	}

	"atalanta_roar_upgrade"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_roar"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_roar"

		"AbilityCastRange"				"600 650 700 750 800"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"100"

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_FLOAT"
				"duration"				"2 2.5 3 3.5 4"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"ms_slow"				"20 25 30 35 40"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"distance"				"600 650 700 750 800"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"width"					"200"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"base_stacks"			"1 2 3 4 5"
			}
			"06"
			{
				"var_type"				"FIELD_INTEGER"
				"base_damage"			"100 175 250 325 400"
			}
			"07"
			{
				"var_type"				"FIELD_INTEGER"
				"echo_damage"			"100"
			}
			"08"
			{
				"var_type"				"FIELD_INTEGER"
				"as_slow"				"50 70 90 110 130"
			}
			"09"
			{
				"var_type"				"FIELD_INTEGER"
				"cast_range"			"450"
			}
			"10"
			{
				"var_type"				"FIELD_FLOAT"
				"duration_locked"			"1 1.25 1.5 1.75 2"
			}
		}
	}

	//=======================================
	// Berserker - Attack of the Beast
	//=======================================

	"atalanta_ora"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_ora"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_INSTANT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_ora"
		"AbilityCastPoint"				"0"

		"AbilityCooldown"				"22 21 20 19 18"

		"AbilityManaCost"				"200"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"			"FIELD_INTEGER"
				"radius"			"200"
			}
			"02"
			{
				"var_type"			"FIELD_FLOAT"
				"width"				"50"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"total_damage"		"-50"
			}
			"04"
			{
				"var_type"			"FIELD_FLOAT"
				"duration"			"6"
			}
			"05"
			{
				"var_type"			"FIELD_INTEGER"
				"reduce_damage"		"-20"
			}
			"06"
			{
				"var_type"			"FIELD_FLOAT"
				"attack_rate"		"1.0"
			}
			"07"
			{
				"var_type"			"FIELD_FLOAT"
				"base_damage"		"10 20 30 40 50"
			}
			"08"
			{
				"var_type"			"FIELD_FLOAT"
				"base_attack_count"	"0"
			}
			"09"
			{
				"var_type"			"FIELD_INTEGER"
				"as_bonus"			"50 75 100 125 150"
			}
			"10"
			{
				"var_type"			"FIELD_INTEGER"
				"attack_range_bonus"	"20 40 60 80 100"
			}
		}
	}

	//=======================================
	// Berserker - Cursed Furiocity
	//=======================================
	"atalanta_pull"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_pull"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_ora"
		"AbilityCastPoint"				"0.1"

		"AbilityCooldown"				"22 21 20 19 18"

		"AbilityManaCost"				"200"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"			"FIELD_INTEGER"
				"radius"			"600 650 700 750 800"
			}
			"02"
			{
				"var_type"			"FIELD_FLOAT"
				"slow_dur"			"2.5"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"damage"			"200 250 300 350 400"
			}
			"04"
			{
				"var_type"			"FIELD_FLOAT"
				"curse_stacks"		"2 4 6 8 10"
			}
			"05"
			{
				"var_type"			"FIELD_INTEGER"
				"ms_slow"			"30 35 40 45 50"
			}
			"06"
			{
				"var_type"			"FIELD_FLOAT"
				"as_slow"			"1.2 1.3 1.4 1.5 1.6"
			}
		}
	}

	//=======================================
	// Berserker - Crossing Arcadia
	//=======================================

	"atalanta_jump"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_jump"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_jump"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"
		
		"AOERadius"						"%radius"
		"AbilityCastRange"				"1100"
		"AbilityCastPoint"				"0.4"
		"AbilityManaCost"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"29 26 23 20 17"

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"speed"					"900"
			}
			"02"
			{
				"var_type"				"FIELD_FLOAT"
				"fly_duration"			"0.8"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"max_height"			"700"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"damage"				"400 480 560 640 720"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"radius"				"400"
			}
			"06"
			{
				"var_type"				"FIELD_INTEGER"
				"curse_stacks"			"6 7 8 9 10"
			}
			"07"
			{
				"var_type"				"FIELD_FLOAT"
				"stun_duration"			"0.7 1.0 1.4 1.7 2.0"
			}
			"08"
			{
				"var_type"				"FIELD_FLOAT"
				"flame_duration"		"1.5 2.0 2.5 3.0 3.5"
			}
		}		
	}

	//=======================================
	// Berserker - Curse
	//=======================================

	"atalanta_curse"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_curse"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_curse"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"AbilityCooldown"				"30"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"			"FIELD_INTEGER"
				"duration"			"7"
			}
			"02"
			{
				"var_type"			"FIELD_FLOAT"
				"amplify_per_stack"	"0.25"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"detonate_damage"	"8"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"max_stack"			"70"
			}
		}
	}

	"atalanta_curse_upgrade"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_curse"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_curse"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"AbilityCooldown"				"30"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"			"FIELD_INTEGER"
				"duration"			"9"
			}
			"02"
			{
				"var_type"			"FIELD_FLOAT"
				"amplify_per_stack"	"0.25"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"detonate_damage"	"12"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"vision"	"10"
			}
			"03"
			{
				"var_type"			"FIELD_INTEGER"
				"max_stack"			"70"
			}
		}
	}

	//=======================================
	// Berserker - Tauropolos Alter
	//=======================================

	"atalanta_tauropolos_alter"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_tauropolos_alter"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK2"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_tauropolos"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"1.0"
		"AbilityManaCost"				"800"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"40 37 34 31 28"

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"damage"				"75 100 125 150 175"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"duration"				"5"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"min_dist"				"10"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"max_dist"				"700"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"explosion_radius"		"200"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"curse_stacks"			"4 5 6 7 8"
			}
		}		
	}

	"atalanta_tauropolos_alter_upgrade"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_tauropolos_alter"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK2"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_tauropolos"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"1.0"
		"AbilityManaCost"				"800"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"40 37 34 31 28"

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"damage"				"150 175 200 225 250"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"duration"				"5"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"min_dist"				"10"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"max_dist"				"700"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"explosion_radius"		"200"
			}
			"05"
			{
				"var_type"				"FIELD_INTEGER"
				"curse_stacks"			"8 9 10 11 12"
			}
		}		
	}

	//=======================================
	// Combo - Tauropolos Skia Thermokrasia
	//=======================================

	"atalanta_skia"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_skia"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_CHANNELED | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_skia"
		"AbilityCastPoint"				"0.1"
		"AbilityChannelTime"			"0.01"

		"AbilityCooldown"				"180"
		"AbilityCastRange"				"2500"	
		"AbilityManaCost"				"800"
		
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"damage"				"2750"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"curse_stacks"			"50"
			}
			"03"
			{
				"var_type"				"FIELD_INTEGER"
				"radius"				"900"
			}
			"04"
			{
				"var_type"				"FIELD_FLOAT"
				"fly_duration"			"3.25"
			}
		}
	}

	"atalanta_evolution_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_attr1"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"14"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"radius"				"300"
			}
		}		
	}
	"atalanta_tornado_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_attr2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"e_pull"				"150"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"e_extra_curse"			"5"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"q_pull"				"100"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"q_extra_curse"			"5"
			}
			"03"
			{
				"var_type"				"FIELD_FLOAT"
				"combo_pull"				"250"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"attack_pull"				"40"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"attack_pull_from_curse"			"0.5"
			}
		}		
	}
	"atalanta_vision_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_vision"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"14"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"extra_curse_damage"	"4"
			}
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"curse_vision"			"10"
			}
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"curse_bonus_duration"	"2"
			}
		}		
	}
	"atalanta_moon_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_moon"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"17"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"roar_damage"			"100"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"tauropolos_curse"		"4"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"tauropolos_bonus_damage"		"75"
			}
			"03"
			{
				"var_type"				"FIELD_FLOAT"
				"percent"				"0.1"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"explosion"				"5"
			}
		}		
	}
	"atalanta_passive_beast"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_beast"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilitySpecial"
		{
			"01"
			{
				"var_type"				"FIELD_INTEGER"
				"e_pull"				"150"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"e_extra_curse"			"4"
			}
			"02"
			{
				"var_type"				"FIELD_INTEGER"
				"q_pull"				"100"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"q_extra_curse"			"2"
			}
			"03"
			{
				"var_type"				"FIELD_FLOAT"
				"combo_pull"				"250"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"	
				"attack_pull"				"40"
			}
			"04"
			{
				"var_type"				"FIELD_INTEGER"
				"attack_pull_from_curse"			"0.5"
			}
		}		
	}
}