"DOTAAbilities"
{
	//=======================================
	// Berserker - Roar
	//=======================================
	"atalanta_roar"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_roar"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_roar"

		"AbilityCastRange"				"600 650 700 750 800"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"100"

		"AbilityValues"
        {
            "duration" "2 2.5 3 3.5 4"
            "ms_slow" "20 25 30 35 40"
            "distance" "600 650 700 750 800"
            "width" "200"
            "base_stacks" "1 2 3 4 5"
            "base_damage" "100 175 250 325 400"
            "echo_damage" "100"
            "as_slow" "50 70 90 110 130"
            "cast_range" "450"
            "duration_locked" "1 1.25 1.5 1.75 2"
        }
	}

	"atalanta_roar_upgrade"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_roar"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL" 
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_roar"

		"AbilityCastRange"				"600 650 700 750 800"
		
		"AbilityCastPoint"				"0.3"
		"AbilityCooldown"				"15 14 13 12 11"
		"AbilityManaCost"				"100"

		"AbilityValues"
        {
            "duration" "2 2.5 3 3.5 4"
            "ms_slow" "20 25 30 35 40"
            "distance" "600 650 700 750 800"
            "width" "200"
            "base_stacks" "1 2 3 4 5"
            "base_damage" "100 175 250 325 400"
            "echo_damage" "100"
            "as_slow" "50 70 90 110 130"
            "cast_range" "450"
            "duration_locked" "1 1.25 1.5 1.75 2"
        }
	}

	//=======================================
	// Berserker - Attack of the Beast
	//=======================================

	"atalanta_ora"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_ora"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_INSTANT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_ora"
		"AbilityCastPoint"				"0"

		"AbilityCooldown"				"22 21 20 19 18"

		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "radius" "200"
            "width" "50"
            "total_damage" "-50"
            "duration" "6"
            "reduce_damage" "-20"
            "attack_rate" "1.0"
            "base_damage" "10 15 20 25 30"
            "base_attack_count" "0"
            "as_bonus" "50 75 100 125 150"
            "attack_range_bonus" "20 40 60 80 100"
        }
	}

	//=======================================
	// Berserker - Cursed Furiocity
	//=======================================
	"atalanta_pull"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_pull"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_5"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_ora"
		"AbilityCastPoint"				"0.1"

		"AbilityCooldown"				"22 21 20 19 18"

		"AbilityManaCost"				"200"
		
		"AbilityValues"
        {
            "radius" "600 650 700 750 800"
            "slow_dur" "2.5"
            "damage" "200 250 300 350 400"
            "curse_stacks" "2 4 6 8 10"
            "ms_slow" "30 35 40 45 50"
            "as_slow" "1.2 1.3 1.4 1.5 1.6"
        }
	}

	//=======================================
	// Berserker - Crossing Arcadia
	//=======================================

	"atalanta_jump"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_jump"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_jump"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"
		
		"AOERadius"						"%radius"
		"AbilityCastRange"				"1100"
		"AbilityCastPoint"				"0.4"
		"AbilityManaCost"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"29 26 23 20 17"

		"AbilityValues"
        {
            "speed" "900"
            "fly_duration" "0.8"
            "max_height" "700"
            "damage" "400 480 560 640 720"
            "radius" "400"
            "curse_stacks" "6 7 8 9 10"
            "stun_duration" "0.7 1.0 1.4 1.7 2.0"
            "flame_duration" "1.5 2.0 2.5 3.0 3.5"
        }		
	}
	//=======================================
	// Berserker - Crossing Arcadia
	//=======================================

	"atalanta_jump_upgrade"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_jump"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_jump"
		"AbilityCastAnimation" 			"ACT_DOTA_CAST_ABILITY_3"
		"AnimationPlaybackRate" 		"1.0"
		
		"AOERadius"						"%radius"
		"AbilityCastRange"				"1100"
		"AbilityCastPoint"				"0.4"
		"AbilityManaCost"				"400"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"29 26 23 20 17"

		"AbilityValues"
        {
            "speed" "900"
            "fly_duration" "0.8"
            "max_height" "700"
            "damage" "400 480 560 640 720"
            "radius" "400"
            "curse_stacks" "6 7 8 9 10"
            "stun_duration" "0.7 1.0 1.4 1.7 2.0"
            "flame_duration" "1.5 2.0 2.5 3.0 3.5"
        }		
	}

	//=======================================
	// Berserker - Curse
	//=======================================

	"atalanta_curse"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_curse"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_curse"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"AbilityCooldown"				"30"
		
		"AbilityValues"
        {
            "duration" "7"
            "amplify_per_stack" "0.3"
            "detonate_damage" "8"
            "max_stack" "100"
        }
	}

	"atalanta_curse_upgrade"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_curse"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_curse"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"AbilityCooldown"				"30"
		
		"AbilityValues"
        {
            "duration" "9"
            "amplify_per_stack" "0.3"
            "detonate_damage" "12"
            "vision" "10"
            "max_stack" "100"
        }
	}

	//=======================================
	// Berserker - Tauropolos Alter
	//=======================================

	"atalanta_tauropolos_alter"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_tauropolos_alter"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK2"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_tauropolos"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"0.85"
		"AbilityManaCost"				"800"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"40 37 34 31 28"

		"AbilityValues"
        {
            "damage" "75 100 125 150 175"
            "duration" "5"
            "min_dist" "10"
            "max_dist" "700"
            "explosion_radius" "200"
            "curse_stacks" "4 5 6 7 8"
        }		
	}

	"atalanta_tauropolos_alter_upgrade"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_tauropolos_alter"
		"MaxLevel"						"5"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"2"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation" 			"ACT_DOTA_ATTACK2"
		"AbilityType"					"DOTA_ABILITY_TYPE_ULTIMATE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_tauropolos"
		"AnimationPlaybackRate" 		"1.0"
		
		"AbilityCastRange"				"500"
		"AbilityCastPoint"				"0.85"
		"AbilityManaCost"				"800"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"40 37 34 31 28"

		"AbilityValues"
        {
            "damage" "150 175 200 225 250"
            "duration" "5"
            "min_dist" "10"
            "max_dist" "700"
            "explosion_radius" "200"
            "curse_stacks" "8 9 10 11 12"
        }		
	}

	//=======================================
	// Combo - Tauropolos Skia Thermokrasia
	//=======================================

	"atalanta_skia"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_skia"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_skia"
		"AbilityCastPoint"				"0.1"
		"AbilityChannelTime"			"0.01"

		"AbilityCooldown"				"180"
		"AbilityCastRange"				"3250"	
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "damage" "2750"
            "curse_stacks" "50"
            "radius" "900"
            "fly_duration" "3.25"
        }
	}

	//=======================================
	// Combo - Tauropolos Skia Thermokrasia
	//=======================================

	"atalanta_skia_upgrade"
	{
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_skia"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_AOE | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY" 
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_ALL"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"AbilityCastAnimation"			"ACT_DOTA_CAST_ABILITY_6"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_skia"
		"AbilityCastPoint"				"0.1"
		"AbilityChannelTime"			"0.01"

		"AbilityCooldown"				"180"
		"AbilityCastRange"				"3250"	
		"AbilityManaCost"				"800"
		
		"AbilityValues"
        {
            "damage" "2750"
            "curse_stacks" "50"
            "radius" "900"
            "fly_duration" "3.25"
        }
	}

	"atalanta_evolution_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_attr1"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"14"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "heal" "15"
            "radius" "300"
        }		
	}
	"atalanta_tornado_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_attr2"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"12"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "e_pull" "150"
            "e_extra_curse" "5"
            "q_pull" "100"
            "q_extra_curse" "5"
            "combo_pull" "250"
            "attack_pull" "40"
            "attack_pull_from_curse" "0.5"
        }		
	}
	"atalanta_vision_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_vision"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"14"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "extra_curse_damage" "4"
            "curse_vision" "10"
            "curse_bonus_duration" "2"
        }		
	}
	"atalanta_moon_attribute"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_lua"
		"ScriptFile"					"abilities/alter_atalanta/atalanta_attributes"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_PSEUDO_QUEUE | DOTA_ABILITY_BEHAVIOR_IGNORE_CHANNEL"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_moon"
		"AbilityCooldown"				"9999"

		"AbilityManaCost"				"17"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "roar_damage" "100"
            "tauropolos_curse" "4"
            "tauropolos_bonus_damage" "75"
            "percent" "0.1"
            "explosion" "5"
        }		
	}
	"atalanta_passive_beast"
	{
		// General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"RequiredLevel"					"1"
		"LevelsBetweenUpgrades"			"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/alter_atalanta/atalanta_beast"
		"AbilityCooldown"				"0"
		"AbilityManaCost"				"0"

		// Time		
		//-------------------------------------------------------------------------------------------------------------

		"AbilityValues"
        {
            "e_pull" "150"
            "e_extra_curse" "4"
            "q_pull" "100"
            "q_extra_curse" "2"
            "combo_pull" "250"
            "attack_pull" "40"
            "attack_pull_from_curse" "0.5"
        }		
	}
	//=======================================
	// Precache
	//=======================================
	"atalanta_alter_precache"
	{
		// General		//------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"MaxLevel"						"1"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_HIDDEN | DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityTextureName"			"custom/medusa/medusa_attribute_monstrous_strength"

		"precache"
		{
			"model"					"models/arthur/arthur_by_zefiroft.vmdl"
			"particle"				"particles/units/heroes/hero_shadow_demon/shadow_demon_shadow_poison_4stack.vpcf"	
			"parictle"				"particles/units/heroes/hero_shadow_demon/shadow_demon_shadow_poison_kill.vpcf"
			"particle"				"particles/atalanta/atalanta_earthshock.vpcf"
			"particle"				"particles/units/heroes/hero_ursa/ursa_fury_sweep_cross.vpcf"
			"particle"				"particles/units/heroes/hero_dark_seer/dark_seer_vacuum.vpcf"
			"particle"				"particles/atalanta/beastmaster_primal_roar.vpcf"
			"particle"				"particles/units/heroes/hero_sniper/sniper_headshot_slow.vpcf"
			"particle"				"particles/atalanta/rider_bellerophon_1.vpcf"
			"particle"				"particles/atalanta/lancer_gae_bolg_hit.vpcf"
			"particle"  			"particles/atalanta/combo_impact_flek.vpcf"
			"particle"  			"particles/atalanta/abyssal_underlord_firestorm_wave.vpcf"
			"particle"  			"particles/atalanta/ruler_purge_the_unjust_a.vpcf"
			"particle"  			"particles/econ/items/drow/drow_arcana/drow_arcana_lifesteal.vpcf"
			"particle"  			"particles/atalanta/atalanta_alter_slam.vpcf"
			"particle"  			"particles/atalanta/juggernaut_blade_fury.vpcf"
			"soundfile"				"soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts"
		}
	}
}